### ISSUE TITLE
Import functions

### ISSUE THREAD

**Issue by nelsonleung** [SchusterLab/quantum-optimal-control#8]
@whitewhim2718 Thank you for fixing the bugs, setting up a nice setup.py, and all the wonderful suggestions!

A quick question — I’m now testing the code and found import errors, and figured I have to make changes from import, for example:
`from helper_functions.grape_functions import c_to_r_mat`

to 

`from quantum_optimal_control.helper_functions.grape_functions import c_to_r_mat`

Once I do this the code works perfectly. Do you have this issue, or it’s just me doing something wrong? Thanks!

**Comment by taalexander** [comment]
@nelsonleung 
 I believe this is working as intended. Before I added the setup.py you could think of all the folders such as helper_functions as separate packages that you could then individually import because you appended the top level folder to the python path. However with the addition of a setup.py we wish to incorporate the individual modules into a uniform package. We do this by making them submodules of `quantum_optimal_control`. 
Thus we now require the import to be of the form `from quantum_optimal_control.helper_functions.grape_functions import c_to_r_mat` as you noted, to import from a specific submodule. Due to the way I layed out the `__init__.py` files, I believe it should also be possible to do `from quantum_optimal_control.grape_functions import c_to_r_mat` and `from quantum_optimal_control import c_to_r_mat`; whether this import structure is something you want allowed is a different question. 

As I noted in issue #3 having to type `import quantum_optimal_control` for every import is quite cumbersome and ugly on the eyes. A new package name would resolve these issues. 

Unfortunately I do  not have a dev environment setup at my lab, but I can check all of this when I'm home tonight.

**Comment by nelsonleung** [comment]
ok! I will update it to the form `from quantum_optimal_control.helper_functions.grape_functions import` for now. Definitely agree the issue #3. Let's settle down a name and update the imports accordingly.
